export default {
   AppStack:{
      AUTHENTICATION:'Authentication',
      LOGIN:'Login',
      SIGNUP:'SignUp',
      VERIFY_OTP:'VerifyOtp',
      HOME:'Home',
      PRIMARY_HOME:'PrimaryHome',
      FORGOT_PASSWORD:'ForgotPassword'

   },
   BottomTab:{
      SOCIAL_HOME:'SocialHome',
      FRIEND_HOME:'FriendHome',
      MARKET_HOME:"MarketHome",
      
      USER_PROFILE:"UserProfile",
      MLM_HOME:'MlmHome',
      
   },
   Market:{
       MARKET:'Market',
       VARIANT_LIST:'VariantList',
       PRODUCT_DETAIL:'ProductDetail',
       ADDRESS:'Address',
       ADDRESS_FORM:'AddressForm',
       SEARCH:'Search',
       CART:'Cart',
       WISH_LIST:'WishList',
       ORDER:'Order',
       PAYMENT:'Payment',
       ORDER_STATUS:'OrderStatus',
       ADDRESS_EDIT_FORM:'MarketAddressEditForm'
   },
   Profile:{
      PROFILE:'Profile',       
      ACCOUNT_SETTINGS:'AccountSettings',
      ADDRESS_BOOK:'AddressBook',
      ADDRESS_EDIT_FORM:'AddressEditForm',
      tracking:{
         TO_VERIFY:'ToVerify',
         TO_SHIP:'ToShip',
         TO_RECEIVE:'ToReceive',
      },
      VIEW_NEW_PROFILE_PIC:'ViewNewProfilePic'
   },
   Social:{
      SOCIAL:'Social',
      CREATE_POST:'CreatePost',         
      CAMERA:'Camera', 
      CAPTURED_PHOTO:'CapturedPhoto', 
      VIEW_POST:'ViewPost',
      FRIENDS:'Friends',
      COMMENTS:'comments',
      VIEW_PROFILE:'ViewProfile',
      STORIES:'Stories',
      MESSENGER:'Messenger',
      CHAT:'chat',
      CHOOSE_FRIEND_TO_CHAT:'ChooseFriendToChat',
      INSPIRE:'Inspire',   
  },
  Friend:{
   FRIEND:'Friend'
 },
 Mlm:{
   MLM:'Mlm',
   REWARD_HISTORY:'RewardHistory'
 }
    
}