export default {
   AppStack:{
      AUTHENTICATION:'Authentication',
      LOGIN:'Login',
      SIGNUP:'SignUp',
      VERIFY_OTP:'VerifyOtp',
      HOME:'Home',

   },
   BottomTab:{
      SOCIAL_HOME:'SocialHome',
      MARKET_HOME:"MarketHome",
      USER_PROFILE:"UserProfile"
   },
   Market:{
       MARKET:'Market',
       VARIANT_LIST:'VariantList',
       PRODUCT_DETAIL:'ProductDetail',
       ADDRESS:'Address',
       ADDRESS_FORM:'AddressForm',
       SEARCH:'Search',
       CART:'Cart',
       WISH_LIST:'WishList',
       ORDER:'Order',
       PAYMENT:'Payment'
   },
   Profile:{
      PROFILE:'Profile',       
      ACCOUNT_SETTINGS:'AccountSettings',
      ADDRESS_BOOK:'AddressBook',
      ADDRESS_EDIT_FORM:'AddressEditForm',
      tracking:{
         TO_VERIFY:'ToVerify',
         TO_SHIP:'ToShip',
         TO_RECEIVE:'ToReceive',
      }
   },
   Social:{
      SOCIAL:'Social',
      CREATE_POST:'CreatePost',         
  }
    
}